export const MUDARLENGTH= 'MUDARLENGTH';
export const MUDARLENGTHBREAK= 'MUDARLENGTHBREAK';
export const MUDARLENGTHSESSION= 'MUDARLENGTHSESSION';
export const MUDARTEMPO= 'MUDARTEMPO';
export const TROCARMODO= 'TROCARMODO';
export const PLAY= 'PLAY';
export const PAUSE= 'PAUSE';
export const RESET= 'RESET';