export const MUDARLENGTH= 'MUDARLENGTH';
export const MUDARLENGTHBREAK= 'MUDARLENGTHBREAK';
export const MUDARLENGTHSESSION= 'MUDARLENGTHSESSION';
export const MUDARTEMPO= 'MUDARTEMPO';
export const PLAY= 'PLAY';

